apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1",
       "kind":"Ingress",
    kubernetes.io/ingress.class: internal
    nginx.ingress.kubernetes.io/rewrite-target: /
  generation: 1
  name: adjust-ingress
spec:
  rules:
  - host: <specify your cname (the website name)>
    http:
      paths:
      - backend:
          serviceName: adjust-api
          servicePort: 80
        path: /
status:
  loadBalancer:
    ingress:
    - {}