kind: Service
apiVersion: v1
metadata:
  name: adjust-api
spec:
  selector:
    app: adjust-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
  # clusterIP: 10.0.171.239
  # type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#     - ip: 192.0.2.127