---
- hosts: localhost
  gather_facts: false
  become: yes
  tasks:
    - name: Build and image and push it to docker hub or registry
      docker_image:
        build:
          path: ..
        name: adjust
        repository: soumyarout80/task_adjust
        tag: 1.0.1
        push: yes
        source: build